const fs=require('fs'),{chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
require('esbuild').buildSync({entryPoints:['src/gen/dungeon.ts'],outfile:'qa/exit-map.cjs',bundle:true,platform:'node',format:'cjs'});
const {createDungeonLayout,isDungeonBlocked}=require('./exit-map.cjs');
function route(map,from,to){const cell=p=>Math.floor(p.z)*map.size+Math.floor(p.x),origin=cell(from),goal=cell(to),parents=new Map([[origin,origin]]),q=[origin];for(let i=0;i<q.length&&!parents.has(goal);i++){const n=q[i],x=n%map.size,z=Math.floor(n/map.size);for(const [dx,dz]of [[1,0],[0,1],[-1,0],[0,-1]]){const a=x+dx,b=z+dz,k=b*map.size+a;if(!parents.has(k)&&!isDungeonBlocked(map,{x:a+.5,z:b+.5})){parents.set(k,n);q.push(k);}}}if(!parents.has(goal))throw Error('No route');let n=goal,path=[to];while(n!==origin){path.push({x:n%map.size+.5,z:Math.floor(n/map.size)+.5});n=parents.get(n);}path.push({x:origin%map.size+.5,z:Math.floor(origin/map.size)+.5});return path.reverse();}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 const seed='exit-4',map=createDungeonLayout(seed);await page.clock.install({time:new Date('2026-09-07T00:00:00Z')});await page.goto('http://127.0.0.1:5173/?seed='+seed);await page.clock.pauseAt(new Date('2026-09-07T00:00:02Z'));await page.screenshot({path:'qa/exit-start-1280.png'});
 await page.evaluate(()=>{window.qaMouse=[];document.addEventListener('mousemove',e=>window.qaMouse.push(e.movementX));});
 await page.locator('#start').click();await page.clock.runFor(32);
 let position={...map.start};const first=map.sockets[0];let yaw=Math.atan2(first.point.x-map.start.x,first.point.z-map.start.z);let mx=640;
 async function face(angle){let delta=angle-yaw;while(delta>Math.PI)delta-=2*Math.PI;while(delta<-Math.PI)delta+=2*Math.PI;await page.evaluate(()=>window.qaMouse=[]);mx-=delta/.002;await page.mouse.move(mx,360);await page.clock.runFor(16);const moves=await page.evaluate(()=>window.qaMouse);yaw-=moves.reduce((a,b)=>a+b,0)*.002;}
 async function go(target){let dx=target.x-position.x,dz=target.z-position.z,d=Math.hypot(dx,dz);if(d<.035)return;await face(Math.atan2(dx,dz));const ms=Math.round(d/3/.016)*16;await page.keyboard.down('KeyW');await page.clock.runFor(ms);await page.keyboard.up('KeyW');position.x+=Math.sin(yaw)*3*ms/1000;position.z+=Math.cos(yaw)*3*ms/1000;}
 await page.screenshot({path:'qa/exit-map-a.png'});
 const path=route(map,position,map.exit.inside);for(const p of path)await go(p);await face(Math.atan2(map.exit.normal.x,map.exit.normal.z));await page.clock.runFor(16);await page.screenshot({path:'qa/exit-door.png'});const before=await page.locator('#overlay').isVisible();
 for(const p of route(map,position,map.exit.outside))await go(p);
 await page.screenshot({path:'qa/exit-clear.png'});const title=await page.locator('#overlay-title').innerText();if(title!=='탈출 성공!')throw Error('Did not clear: '+title+' '+JSON.stringify({position,yaw,exit:map.exit}));
 const description=await page.locator('#overlay-description').innerText();await page.clock.runFor(5000);const frozen=description===await page.locator('#overlay-description').innerText();await page.locator('#start').click();await page.clock.runFor(32);const newSeed=await page.locator('#seed').innerText();await page.screenshot({path:'qa/exit-restart.png'});
 for(const width of [375,768]){await page.setViewportSize({width,height:900});await page.screenshot({path:`qa/exit-start-${width}.png`});}
 fs.writeFileSync('qa/exit-browser-results.json',JSON.stringify({seed,before,title,description,frozen,newSeed,errors},null,2));console.log({title,frozen,newSeed,errors});
 }catch(e){await page.screenshot({path:'qa/exit-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
